const ISO_COUNTRY_CODES = [
  "AD",
  "AE",
  "AF",
  "AG",
  "AI",
  "AL",
  "AM",
  "AO",
  "AR",
  "AT",
  "AU",
  "AW",
  "AZ",
  "BA",
  "BB",
  "BD",
  "BE",
  "BF",
  "BG",
  "BH",
  "BI",
  "BJ",
  "BM",
  "BN",
  "BO",
  "BR",
  "BS",
  "BT",
  "BW",
  "BY",
  "BZ",
  "CA",
  "CD",
  "CF",
  "CG",
  "CH",
  "CI",
  "CL",
  "CM",
  "CN",
  "CO",
  "CR",
  "CU",
  "CV",
  "CY",
  "CZ",
  "DE",
  "DJ",
  "DK",
  "DM",
  "DO",
  "DZ",
  "EC",
  "EE",
  "EG",
  "ES",
  "ET",
  "FI",
  "FJ",
  "FR",
  "GA",
  "GB",
  "GD",
  "GE",
  "GH",
  "GM",
  "GN",
  "GQ",
  "GR",
  "GT",
  "GW",
  "GY",
  "HN",
  "HR",
  "HT",
  "HU",
  "ID",
  "IE",
  "IL",
  "IN",
  "IQ",
  "IR",
  "IS",
  "IT",
  "JM",
  "JO",
  "JP",
  "KE",
  "KG",
  "KH",
  "KM",
  "KN",
  "KR",
  "KW",
  "KZ",
  "LA",
  "LB",
  "LC",
  "LI",
  "LK",
  "LR",
  "LS",
  "LT",
  "LU",
  "LV",
  "LY",
  "MA",
  "MC",
  "MD",
  "ME",
  "MG",
  "MK",
  "ML",
  "MM",
  "MN",
  "MR",
  "MT",
  "MU",
  "MV",
  "MW",
  "MX",
  "MY",
  "MZ",
  "NA",
  "NE",
  "NG",
  "NI",
  "NL",
  "NO",
  "NP",
  "NZ",
  "OM",
  "PA",
  "PE",
  "PG",
  "PH",
  "PK",
  "PL",
  "PT",
  "PY",
  "QA",
  "RO",
  "RS",
  "RU",
  "RW",
  "SA",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SI",
  "SK",
  "SL",
  "SM",
  "SN",
  "SO",
  "SR",
  "SS",
  "SV",
  "SY",
  "SZ",
  "TD",
  "TG",
  "TH",
  "TJ",
  "TL",
  "TM",
  "TN",
  "TR",
  "TT",
  "TW",
  "TZ",
  "UA",
  "UG",
  "US",
  "UY",
  "UZ",
  "VA",
  "VC",
  "VE",
  "VN",
  "VU",
  "WS",
  "YE",
  "ZA",
  "ZM",
  "ZW",
];

export const CALLING_CODE_OPTIONS = [
  { countryCode: "BR", flag: "🇧🇷", callingCode: "+55" },
  { countryCode: "US", flag: "🇺🇸", callingCode: "+1" },
  { countryCode: "CA", flag: "🇨🇦", callingCode: "+1" },
  { countryCode: "PT", flag: "🇵🇹", callingCode: "+351" },
  { countryCode: "GB", flag: "🇬🇧", callingCode: "+44" },
  { countryCode: "ES", flag: "🇪🇸", callingCode: "+34" },
  { countryCode: "FR", flag: "🇫🇷", callingCode: "+33" },
  { countryCode: "DE", flag: "🇩🇪", callingCode: "+49" },
  { countryCode: "IT", flag: "🇮🇹", callingCode: "+39" },
  { countryCode: "AR", flag: "🇦🇷", callingCode: "+54" },
  { countryCode: "CL", flag: "🇨🇱", callingCode: "+56" },
  { countryCode: "CO", flag: "🇨🇴", callingCode: "+57" },
  { countryCode: "MX", flag: "🇲🇽", callingCode: "+52" },
  { countryCode: "PE", flag: "🇵🇪", callingCode: "+51" },
  { countryCode: "UY", flag: "🇺🇾", callingCode: "+598" },
  { countryCode: "PY", flag: "🇵🇾", callingCode: "+595" },
  { countryCode: "JP", flag: "🇯🇵", callingCode: "+81" },
  { countryCode: "CN", flag: "🇨🇳", callingCode: "+86" },
  { countryCode: "IN", flag: "🇮🇳", callingCode: "+91" },
  { countryCode: "AU", flag: "🇦🇺", callingCode: "+61" },
  { countryCode: "NZ", flag: "🇳🇿", callingCode: "+64" },
  { countryCode: "ZA", flag: "🇿🇦", callingCode: "+27" },
];

export const getCountryOptions = (language: string) => {
  const displayNames = new Intl.DisplayNames([language], { type: "region" });

  return ISO_COUNTRY_CODES.map((code) => ({
    code,
    name: displayNames.of(code) ?? code,
  })).sort((firstCountry, secondCountry) =>
    firstCountry.name.localeCompare(secondCountry.name, language),
  );
};
