apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: backend-image

          imagePullPolicy: Always

          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: NODE_ENV

            - name: PORT
              value: "4000"

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: MONGO_URI

            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: RESEND_API_KEY

            - name: APP_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: APP_URL

            - name: DOMAIN
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DOMAIN

            - name: PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: PROJECT_NAME
          ports:
            - containerPort: 4000
