export enum AuditAction {
  //USER
  LOGIN_SUCCEDED = "LOGIN_SUCCESS",
  LOGIN_FAILED = "LOGIN_FAILED",
  CREATED_USER = "CREATED_USER",
  USER_CONFIRM_EMAIL_RESEND = "USER_CONFIRM_EMAIL_RESEND",
  USER_CONFIRMED_EMAIL = "USER_CONFIRMED_EMAIL",
  UPDATED_USER = "UPDATED_USER",
  USER_DEACTIVATED = "USER_DEACTIVATED",
  USER_DELETED = "USER_DELETED",
  USER_PASSWORD_SET = "USER_PASSWORD_SET",
}
